# Generated by Django 5.2.4 on 2025-07-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
