# Generated by Django 5.2.4 on 2025-07-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_description_category_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
    ]
